#!/bin/zsh
cd $HOME
system_type=$(uname -s)
device_name=$(scutil --get ComputerName)
grey=$(tput setaf 8)
red=$(tput setaf 9)
green=$(tput setaf 10)
yellow=$(tput setaf 11)
reset=$(tput sgr0)

function log_info() {
  echo "${grey}[$(date '+%Y-%m-%d %H:%M:%S')]${reset} ${green}INFO${reset} $1"
}
function log_warn() {
  echo "${grey}[$(date '+%Y-%m-%d %H:%M:%S')]${reset} ${yellow}WARN${reset} $1"
}
function log_error() {
  echo "${grey}[$(date '+%Y-%m-%d %H:%M:%S')]${reset} ${red}ERROR${reset} $1"
}

function passport() {
  if [ "$system_type" != "Darwin" ]; then
    log_error "Wrong device. Aborting..."
    exit 1
  fi
}

function brew_bundle() {
  if [ -f "$HOME/.Brewfile" ]; then
    log_info "Installing brew packages..."
    brew bundle --global --quiet
  else
    log_error "Brewfile not exists. Aborting..."
    exit 1
  fi
}

function rlib_environment() {
  if [ ! -d "/usr/local/share/rlibs/" ]; then
    log_info "Creating customized R library directory..."
    mkdir /usr/local/share/rlibs/
  else
    log_warn "Customized R library directory exits. Ignoring..."
  fi
}

function macos_customize() {
  # Refer to ~/.macos — https://mths.be/macos
  log_info "Fitting some customized changes..."

  # Close any open System Preferences panes, to prevent them from overriding
  osascript -e 'tell application "System Preferences" to quit'

  # Ask for the administrator password upfront
  sudo -v

  # General
  # Always show scrollbars
  # Possible values: `WhenScrolling`, `Automatic` and `Always`
  defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"
  # Disable smart dashes as they’re annoying when typing code
  defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
  # Disable automatic capitalization
  defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
  # Disable automatic period substitution
  defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
  # Set menubar digital clock format
  defaults write com.apple.menuextra.clock DateFormat -string "EEE HH:mm"

  # Dock
  # Enable highlight hover effect for the grid view of a stack
  defaults write com.apple.dock mouse-over-hilite-stack -bool true
  # Put dock on the left
  defaults write com.apple.dock orientation -string left
  # Enable the magic zoom animation
  defaults write com.apple.dock magnification -bool true
  # Minimize windows into application’s icon
  defaults write com.apple.dock minimize-to-application -bool true

  # Finder
  # allow quitting via ⌘ + Q; doing so will also hide desktop icons
  defaults write com.apple.finder QuitMenuItem -bool true
  # set Downloads as the default location for new Finder windows
  defaults write com.apple.finder NewWindowTarget -string "PfLo"
  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Downloads/"
  # Keep folders on top when sorting by name
  defaults write com.apple.finder _FXSortFoldersFirst -bool true
  # Avoid creating .DS_Store files on network or USB volumes
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
  # Disable disk image verification
  defaults write com.apple.frameworks.diskimages skip-verify -bool true
  defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
  defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
  # Use list view in all Finder windows by default
  # View by Icon(icnv), List(Nlsv), Column(clmv), CoverFlow(Flwv)
  defaults write com.apple.finder FXPreferredViewStyle -string "clsv"
  # Disable the warning before emptying the Trash
  defaults write com.apple.finder WarnOnEmptyTrash -bool false
  # Show item info to the right of the icons on the desktop
  /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist
}

function macos_customize_desktop() {
  # Energy saving
  sudo pmset -a sleep 45
  sudo pmset -a displaysleep 45
  sudo pmset -a hibernatemode 0
  sudo pmset -a proximitywake 0

  # Dock
  # Set the icon size of Dock items
  defaults write com.apple.dock tilesize -int 64
  defaults write com.apple.dock largesize -int 73
}

function macos_customize_laptop() {
  # Trackpad
  # Enable tap to click
  defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
  # Enable two finger right click
  defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -bool true
  # Use four finger gesture
  defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture -int 2
  defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerVertSwipeGesture -int 2
  defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerHorizSwipeGesture -int 0
  defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerVertSwipeGesture -int 0
  # Enable three finger dragging
  defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
  
  # Dock
  # Enable secret "suck" minimize effect for less frame dropping
  defaults write com.apple.dock mineffect -string suck
  # Set the icon size of Dock items
  defaults write com.apple.dock tilesize -int 52
  defaults write com.apple.dock largesize -int 68
  # Disable show recents
  defaults write com.apple.dock show-recents -bool false
}

function wrap_up() {
  log_info "Reloading..."
  killall SystemUIServer
  killall Dock
  killall Finder
}


passport
brew_bundle
rlib_environment
macos_customize
if [ "$device_name" = "derbalkonRio" ]; then
  macos_customize_desktop
else
  if [ "$device_name" = "derbalkon" ]; then
    macos_customize_laptop
  else
    log_warn "Hmmm... Looks like an unfamiliar Mac."
  fi
fi
wrap_up

log_info "Done. Some of these changes require a logout/restart to take effect."
